# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 00:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20170223_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='jumbtron_bg_color',
            new_name='jumbotron_bg_color',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='jumbtron_text_color',
            new_name='jumbotron_text_color',
        ),
    ]
