# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20170223_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='show_nav',
            field=models.BooleanField(default=True, help_text='Show Navigation Bar?'),
        ),
    ]
